### PR TITLE
StudentCellDelegate

### PR DESCRIPTION
**Pull request by kevinrandrup**
Added StudentCellDelegate protocol and delegate in StudentCell to let
Controllers hook onto the StudentCellDelegate to be notified when the state changes (so they can perform the segue)

I also added a .gitignore so change to unimportantly Xcode project files don't show up

### CODE REVIEW

**Comment by chieger** [comment]
Hi Kevin,

Thank you so much for taking the time to not only solve the delegate and protocol problems I was having, but also provide constructive tips on some of the other elements of the code! I really anticipate the comments to help me follow the logic, as of course I want to learn how to reproduce this on future projects. 

This was my first stackoverflow question, a bit intimidated as a beginner. Thanks for your time and support on this!

Best,
Charlie

**Comment by kevinrandrup** [comment]
I was happy to be able to help you; best of luck on your project.
StackOverflow can be a little scary as a beginner but you wrote a decent question explaining your problem. 

Speaking of that, the answer that the other guy posted is what I did so you can accept it; it's a solution to your problem and may help someone else later down the road

**Comment by chieger** [comment]
I have encountered another couple obstacles as the project progresses.

1) the built in vertical scrolling action the table view had seems to not work anymore. I thought the pan gestures I added to the cells might be interfering, so I added 

    UIGestureRecognizerDelegate 
as well as

```Swift
func gestureRecognizer(UIGestureRecognizer,shouldRecognizeSimultaneouslyWithGestureRecognizer:UIGestureRecognizer) -> Bool {
        return true
    }

```

to the view controller containing the table view. That didn't seem to solve the problem...

2) when I dismissViewControllerAnimated in the CoreValueViewController to return to the StudentListViewController, I need all the stuff in the cell to reset it's position. What i'd like to do is something like: 

```Swift
@IBAction func onBackButton(sender: AnyObject) {
        dismissViewControllerAnimated(true, completion: { () -> Void in
            var studentListViewController = self.storyboard!.instantiateViewControllerWithIdentifier("StudentListViewController") as! StudentListViewController
            
            var cell = studentListViewController.tableView.dequeueReusableCellWithIdentifier("StudentCell") as! StudentCell
            
            cell.cellView.center = cell.initialCenter
            cell.setupIcons()
        })

```
the above seems to get me access to the variables in the StudentCell UITableViewCell but when I run it, it get: unexpectedly found nil while unwrapping an Optional value.

Maybe there is a better way to achieve the desired results all together?

**Comment by chieger** [comment]
I was able to "sort of" fix the cell to reset to its starting position by adding:
```Swift    
cell.cellView.frame = cell.contentView.bounds
```
into 
    
```Swift
func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
```
it does reset the cell, but most of the time there is a **significant lag** after the previous view controller is dismissed.
I tried to doing the same in
```Swift
override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated);
```
but that did not seem to work, even though I was able to do other things like reset the background color of the content view of the cell by adding it to viewWillAppear

flexbuck 3 1

**Pull request merged**
